package fans.umamusume.www.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLotteryUser<M extends BaseLotteryUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setLid(java.lang.Integer lid) {
		set("lid", lid);
	}
	
	public java.lang.Integer getLid() {
		return getInt("lid");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("entry_time", entryTime);
	}
	
	public java.util.Date getEntryTime() {
		return get("entry_time");
	}

}
