package fans.umamusume.www.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 0.技能详情页面
1.支援卡详情页面
2.相性一览页面
3.适性修正页面
4.公告详情页面
5.留言板
6.马娘详情
7.支援卡一览
8.马娘一览
9.育成模拟
10.种马支援卡搜索
	 */
	public void setTarget1(java.lang.Integer target1) {
		set("target1", target1);
	}
	
	/**
	 * 0.技能详情页面
1.支援卡详情页面
2.相性一览页面
3.适性修正页面
4.公告详情页面
5.留言板
6.马娘详情
7.支援卡一览
8.马娘一览
9.育成模拟
10.种马支援卡搜索
	 */
	public java.lang.Integer getTarget1() {
		return getInt("target1");
	}

	/**
	 * sub id
	 */
	public void setTarget2(java.lang.Integer target2) {
		set("target2", target2);
	}
	
	/**
	 * sub id
	 */
	public java.lang.Integer getTarget2() {
		return getInt("target2");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}
	
	public java.lang.Integer getPriority() {
		return getInt("priority");
	}

	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}
	
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
