#namespace("user")
#include("user.sql")
#end
#namespace("food")
#include("food.sql")
#end
#namespace("statistic")
#include("statistic.sql")
#end
#namespace("share")
#include("share.sql")
#end
#namespace("target")
#include("target.sql")
#end
#namespace("shortUrl")
#include("short-url.sql")
#end