package fans.umamusume.www.common.model;

import fans.umamusume.www.common.model.base.BaseAnnouncement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Announcement extends BaseAnnouncement<Announcement> {
	public static final Announcement dao=new Announcement().dao();
}
