package fans.umamusume.www.common.model;

import fans.umamusume.www.common.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
    public static final Comment dao = new Comment().dao();
}
