package fans.umamusume.www.common.model;

import fans.umamusume.www.common.model.base.BaseLotteryUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryUser extends BaseLotteryUser<LotteryUser> {
    public static final LotteryUser dao = new LotteryUser().dao();
}
