package fans.umamusume.www.common.model;

import fans.umamusume.www.common.model.base.BaseLottery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lottery extends BaseLottery<Lottery> {
    public static final Lottery dao = new Lottery().dao();
}
