package fans.umamusume.www.common.model;

import fans.umamusume.www.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

}
